### ISSUE TITLE
not working with Internet Explorer

### ISSUE THREAD

**Issue by bernhardhas** [rainabba/jquery-table2excel#33] opened 2016-02-29 08:07 UTC
On Internet-Explorer 9 and 10 an error occured.
And with Internet-Explorer-11 the result is only one cell with the value "{table0}"

need help ....

thank you !

**Comment by LittleBigThing** [comment] 2016-03-19 16:30
Same problem here? Any ideas? Would love to help testing...

**Comment by MiniApp** [comment] 2016-04-01 07:05
i also have a same problem

**Comment by rainabba** [comment] 2016-06-02 12:04
Duplicate of https://github.com/rainabba/jquery-table2excel/issues/19

**Closed by rainabba** 2016-06-02 12:04 UTC
