### ISSUE TITLE
Open error in excel

### ISSUE THREAD

**Issue by kesiala** [rainabba/jquery-table2excel#8] opened 2015-04-20 10:48 UTC
Hi, 
i download the latest versión of js file, after read all issues, when i save the file, and then i try to open, the Excel file return an error about the type of the file or the extensión.
I don't know what more to do.
Thanks

**Comment by ferman2147** [comment] 2015-04-20 15:01
find xlsx extension in the table2excel.js file and change it to xls. I did it and it worked for me.

**Comment by kesiala** [comment] 2015-04-20 15:31
now i have changed this and the file opened, but in cell A1 put "{table0}" and anything else more.
:(

**Comment by ferman2147** [comment] 2015-04-21 05:28
I can't really see why it happens, but I think you should check your html code where you create the table, you might be missing a tag or something.

**Comment by kesiala** [comment] 2015-04-21 07:23
i have copied the example and happen the same. i don't what i am doing wrong.

**Comment by rainabba** [comment] 2015-04-22 14:48
Changing the extension to .xls is likely to cause another unique set of issues because the format is xlsx, not xls (one is XML, the other MS specific binary). If you want to provide a public page, I can check out your implementation, but a number of people have used the plugin so the only thing I can conclude is browser incompatibility. What browser are you using kesiala?

**Comment by TorbjornB** [comment] 2015-04-23 08:43
Hello
I also get an error when using the xlsx file ending, and excel 2013 refuses to open the file. If I change the extension to xls, Excel throws a warning that the file format doesnt match the file extension, but the file opens, and the content of the file is correct. 
I tested this with chrome 42 and Excel 2013 on win 8.1

**Comment by ferman2147** [comment] 2015-04-23 12:08
@TorbjornB same here. If we could figure out this and find a solution, then I'd most likely be able to read our excel files via PHPExcel. (That's what I need to get done for one of my recent projects.)

**Comment by tafs7** [comment] 2015-04-23 19:46
@rainabba just curious....what version of Excel are you testing with?  I have a suspicion that the format you are generating is not compatible with Excel 2013.

I just downloaded the sample HTML file and the src JS, and cannot open the resulting file in Excel:

![image](https://cloud.githubusercontent.com/assets/671795/7305944/6d693868-e9c7-11e4-9c3c-78d20fb23cd7.png)

**Comment by lomholdt** [comment] 2015-04-30 15:59
XLSX is not working for me either. I'm using the Excel Preview for Mac. If I change the file extension to .xls it only give me the error below, but the file opens and works perfectly.
![screen shot 2015-04-30 at 17 58 59 1](https://cloud.githubusercontent.com/assets/1733744/7416864/9e235600-ef62-11e4-8be4-d0cdeb6dca20.png)

**Comment by mukilteo** [comment] 2015-05-01 07:39
The only way I could get this to work was to rename the file to .html and open in Excel, but that solution won't work for our clients :(

**Comment by mpryvkin** [comment] 2015-07-17 22:17
+1

**Comment by rainabba** [comment] 2015-07-18 22:14
if someone can figure out how to make Excel play nice with [its own format](https://en.wikipedia.org/wiki/Microsoft_Office_XML_formats) or find the actual formatting error in this plugin, then something can be done. The reality is that this is all a hack of a hack of a hack and not meant for production. I shared the plugin because I thought others might benefit. I make no claims as to other software though and Excel is a finicky beast.

Try saving from Excel as .xlsx and you'll find that it's not even XML, it's actually a ZIP archive full of stuff, even for a sheet one a single value in a single cell. Assuming someone could replicate all the contents correctly, you'd have to then ZIP using JS Zip library (which may be the "right way" to get Excel to shut up).

The fact that you CAN actually open in Excel (after ignoring the "error") or in Open Office should demonstrate that the issue isn't the file, but the app.

If you have ideas, please submit a PR, otherwise, this is way out of scope of what I'm looking to support, but I'd be happy if this project helped someone else come up with a better solution so feel free to fork too.

**Closed by rainabba** 2015-07-18 22:14 UTC
Labels: bug
